artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url : https://drive.google.com/file/d/1ch8ped7WxNktB6wIFonI65-T54pm187n/view?usp=sharing
  local_data_file: artifacts/data_ingestion/kidney-CT_Scan.zip
  unzip_dir: artifacts/data_ingestion


# prepare base mode (VGG-16)
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_model_path: artifacts/prepare_base_model/updated_model.h5


# train model
train_model:
  training_data_dir: artifacts/data_ingestion/kidney-CT_Scan/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
  root_dir: artifacts/train_model
  model_path: artifacts/train_model/model.h5
